(function(n){function q(a,c){var b=a.toString();if(b.length<c)for(var d=c-b.length,e=0;e<d;e++)b="0"+b;return b}function H(a,c,b){"undefined"===typeof b&&(b={am:"am",pm:"pm",AM:"AM",PM:"PM"});for(var d=j=0;"undefined"!==typeof c[d]||"undefined"!==typeof a[j];)if("%"===c[d])switch(c[d+1]){case "h":var e=parseInt(a.substring(j,j+2),10);if(isNaN(e)||0>=e||12<e)return!1;d+=2;j+=2;break;case "H":e=parseInt(a.substring(j,j+2),10);if(isNaN(e)||0>e||24<=e)return!1;d+=2;j+=2;break;case "g":e=parseInt(a.substring(j,
j+2),10);var k=parseInt(a.substring(j,j+1),10);if(!isNaN(e)&&10<=e&&12>=e){d+=2;j+=2;break}else if(!isNaN(k)&&1<=k&&9>=k){d+=2;j+=1;break}return!1;case "G":e=parseInt(a.substring(j,j+2),10);k=parseInt(a.substring(j,j+1),10);if(!isNaN(e)&&10<=e&&23>=e){d+=2;j+=2;break}else if(!isNaN(k)&&1<=k&&9>=k){d+=2;j+=1;break}return!1;case "i":e=parseInt(a.substring(j,j+2),10);if(isNaN(e)||0>e||60<=e)return!1;d+=2;j+=2;break;case "a":e=b.am.length;k=a.substring(j,j+e);if(k!==b.am&&k!==b.pm)return!1;d+=2;j+=e;
break;case "A":e=b.AM.length;k=a.substring(j,j+e);if(k!==b.AM&&k!==b.PM)return!1;d+=2;j+=e;break;default:if(c[d]!==a[j])return!1;d+=1;j+=1}else{if(c[d]!==a[j])return!1;d+=1;j+=1}return!0}function r(a){var c=a.match(/\d{1,2}:\d\d/),b=a.match(/(a.m.|p.m.|am|pm|A.M.|P.M.|AM|PM)/);return c?(c=c[0].split(":"),a=parseInt(c[0],10),c=parseInt(c[1],10),24<=a||60<=c||b&&13<=a?null:b?"A"===b[0].charAt(0)||"a"===b[0].charAt(0)?a%12*60+c:60*(a%12+12)+c:60*a+c):-1!=a.search("noon")?720:-1!=a.search("midnight")?
0:null}function I(a,c,b){"undefined"===typeof b&&(b={am:"am",pm:"pm",AM:"AM",PM:"PM"});for(var d=j=0,e,k,g,h;"undefined"!==typeof c[d]||"undefined"!==typeof a[j];)if("%"===c[d])switch(c[d+1]){case "h":var f=parseInt(a.substring(j,j+2),10);if(isNaN(f)||0>=f||12<f)return null;e=f;d+=2;j+=2;break;case "H":f=parseInt(a.substring(j,j+2),10);if(isNaN(f)||0>f||24<=f)return null;k=f;d+=2;j+=2;break;case "g":f=parseInt(a.substring(j,j+2),10);var l=parseInt(a.substring(j,j+1),10);if(!isNaN(f)&&10<=f&&12>=f){e=
f;d+=2;j+=2;break}else if(!isNaN(l)&&1<=l&&9>=l){e=l;d+=2;j+=1;break}return null;case "G":f=parseInt(a.substring(j,j+2),10);l=parseInt(a.substring(j,j+1),10);if(!isNaN(f)&&10<=f&&23>=f){k=f;d+=2;j+=2;break}else if(!isNaN(l)&&1<=l&&9>=l){k=l;d+=2;j+=1;break}return null;case "i":g=parseInt(a.substring(j,j+2),10);if(isNaN(g)||0>g||60<=g)return null;d+=2;j+=2;break;case "a":f=b.am.length;h=a.substring(j,j+f);if(h!==b.am&&h!==b.pm)return null;d+=2;j+=f;break;case "A":f=b.AM.length;h=a.substring(j,j+f);
if(h!==b.AM&&h!==b.PM)return null;d+=2;j+=f;break;default:if(c[d]!==a[j])return null;d+=1;j+=1}else{if(c[d]!==a[j])return null;d+=1;j+=1}return g||0==g?h&&e?h===b.am||h===b.AM?e%12*60+g:e%12*60+720+g:k||0==k?0==k?0==g?60:k+g:60*k+g:null:null}function p(a,c,b){return c>b?c<=a||a<=b:c<=a&&a<=b}function t(a,c){for(var b=a.options,d=b.length,e=0;e<d;e++)if(b[e].value==c&&0==b[e].disabled)return b[e].selected=!0;return!1}function y(a,c,b){var d=[];if(a<c)a=Math.floor(a/60);else{for(a=Math.floor(a/60);24>
a;a+=b)d.push(a);a=0}for(;a<=Math.floor(c/60);a+=b)d.push(a);return d}function C(a,c){var b=a.options,d=b.length;if(parseInt(b[0],10)==c)n(a).scrollTop(0);else for(var e=n(a).height(),k=e/n(a).prop("size"),g=1;g<d;g++){var h=parseInt(b[g-1].value,10),f=parseInt(b[g].value,10);if(f==c){n(a).scrollTop(k*(g+.5)-e/2);break}if(h>f){if(h<c||c<f){n(a).scrollTop(k*g-e/2);break}}else if(h<c&&c<f){n(a).scrollTop(k*g-e/2);break}}}function D(a,c){var b=a.options,d=b.length;if(parseInt(b[0],10)==c)n(a).scrollTop(0);
else for(var e=n(a).height(),k=e/n(a).prop("size"),g=1;g<d;g++){var h=parseInt(b[g-1].value,10),f=parseInt(b[g].value,10);if(f==c){n(a).scrollTop(k*(g+.5)-e/2);break}else if(h<c&&c<f){n(a).scrollTop(k*g-e/2);break}}}function z(a,c,b){if("hour"===a){for(var d=b.find(".hour-select").get(0);d.firstChild;)d.removeChild(d.firstChild);if(c.use12HourClock)if("am"===b.find(".ampm-button").text()){var e=c.hour_data_am.length;for(b=0;b<e;b++){a=document.createElement("option");var k=c.hour_data_am[b].hour;
a.value=k;a.innerHTML=q(k,2);c.hour_data_am[b].disabled&&(a.disabled=!0);d.appendChild(a)}}else for(e=c.hour_data_pm.length,b=0;b<e;b++)a=document.createElement("option"),k=c.hour_data_pm[b].hour,a.value=k,a.innerHTML=q(k,2),c.hour_data_pm[b].disabled&&(a.disabled=!0),d.appendChild(a);else for(e=c.hour_data_24.length,b=0;b<e;b++)a=document.createElement("option"),k=c.hour_data_24[b].hour,a.value=k,a.innerHTML=q(k,2),c.hour_data_24[b].disabled&&(a.disabled=!0),d.appendChild(a)}else if("minute"===a)for(d=
b.find(".min-select").get(0),c=c.is_set_time_step?c.timeStep:c.minStep,b=0;60>b;b+=c)a=document.createElement("option"),a.value=b,a.innerHTML=q(b,2),d.appendChild(a)}function A(a,c,b){if("hour"===a&&c.is_set_minmax_time){a=b.find(".hour-select").get(0);for(var d=a.value;a.firstChild;)a.removeChild(a.firstChild);if(c.use12HourClock){var e=b.find(".ampm-button").text();if("am"===e){var k=c.hour_data_am.length;for(e=0;e<k;e++){var g=document.createElement("option"),h=c.hour_data_am[e].hour;g.value=h;
g.innerHTML=q(h,2);c.hour_data_am[e].disabled&&(g.disabled=!0);a.appendChild(g)}}else for(k=c.hour_data_pm.length,e=0;e<k;e++)g=document.createElement("option"),h=c.hour_data_pm[e].hour,g.value=h,g.innerHTML=q(h,2),c.hour_data_pm[e].disabled&&(g.disabled=!0),a.appendChild(g)}d&&(C(a,d),t(a,d)&&A("minute",c,b))}else if("minute"===a){d=b.find(".hour-select");a=b.find(".min-select").get(0);k=d.prop("selectedIndex");h=parseInt(d.val(),10);d=a.value;e=b.find(".ampm-button").text();c.use12HourClock?"am"===
e?(b=c.hour_data_am[k],h%=12):(b=c.hour_data_pm[k],h=h%12+12):b=c.hour_data_24[k];for(;a.firstChild;)a.removeChild(a.firstChild);g=b.min_minute;e=b.max_minute;g=void 0!=g?g:0;e=void 0!=e?e:59;if(c.is_set_time_step){k=c.timeStep;var f=r(c.minTime);h=60*h+g;g+=(k-(f>h?h+1440-f:h-f)%k)%k}else k=c.minStep,g=Math.ceil(g/k)*k;h=e;for(e=g;e<=h;e+=k)g=document.createElement("option"),g.value=e,g.innerHTML=q(e,2),a.appendChild(g);if(c.is_set_disabled_time)for(h=a.options,k=h.length,c=c.disableTimeRanges.length,
e=0;e<c;e++)if(g=b["disable_start_minute"+e],f=b["disable_end_minute"+e],"undefined"!==typeof g||"undefined"!==typeof f)if(g<=f)for(var l=0;l<k;l++){var m=parseInt(h[l].value,10);g<=m&&m<=f&&(h[l].disabled=!0)}else for(l=0;l<k;l++)m=parseInt(h[l].value,10),g<=m?h[l].disabled=!0:m<=f&&(h[l].disabled=!0);d&&(D(a,d),t(a,d))}}function x(a,c,b){var d=parseInt(c.find(".hour-select").val(),10),e=parseInt(c.find(".min-select").val(),10);isNaN(d)||isNaN(e)||(e=a.timeFormat.replace("%g",0==d||12==d?12:d%12).replace("%G",
d).replace("%h",q(0==d||12==d?12:d%12,2)).replace("%H",q(d,2)).replace("%i",q(e,2)),c=a.use12HourClock?c.find(".ampm-button").text():12>d?"am":"pm",e=e.replace("%a",a.ampmText[c]).replace("%A",a.ampmText[c.toUpperCase()]),b.val(e))}function E(a){var c=a.data("timepicker-settings");a=document.createElement("div");var b=document.createElement("div"),d=document.createElement("div"),e=document.createElement("div"),k=document.createElement("div");k.innerHTML=c.hourHeaderText;var g=document.createElement("div");
g.innerHTML=c.minHeaderText;var h=document.createElement("select");h.setAttribute("size",c.selectSize);h.setAttribute("tabindex","-1");var f=document.createElement("select");f.setAttribute("size",c.selectSize);f.setAttribute("tabindex","-1");var l=document.createElement("button");l.setAttribute("tabindex","-1");l.innerHTML=c.okButtonText;var m=document.createElement("button");m.setAttribute("tabindex","-1");m.innerHTML=c.cancelButtonText;d.appendChild(h);d.appendChild(f);e.appendChild(l);e.appendChild(m);
a.appendChild(d);a.className="my-timepicker-div";b.className="row";d.className="row sel_time";e.className="row";k.className="text-center col-6";g.className="text-center col-6";l.className="col-6 btn btn-outline-primary ok-button";m.className="col-6 btn btn-outline-secondary cancel-button";c.use12HourClock?(n(a).css("width","19.2rem"),k.className="text-center col-5",g.className="text-center col-5",h.className="form-control col-5 hour-select",f.className="form-control col-5 min-select",c=document.createElement("button"),
b=document.createElement("span"),c.setAttribute("tabindex","-1"),c.innerHTML="am",b.appendChild(c),d.appendChild(b),c.className="btn btn-primary ampm-button",b.className="col-2 my-auto"):(h.className="form-control col-6 hour-select",f.className="form-control col-6 min-select");return n(a)}function F(a,c){var b=c.data("timepicker-settings");if(b.use12HourClock)a.find(".ampm-button").on("click",function(){var d=n(this);"pm"===d.html()?d.html("am"):d.html("pm");A("hour",b,a)});a.find(".hour-select").on("change click",
function(){(b.is_set_time_step||b.is_set_minmax_time||b.is_set_disabled_time)&&A("minute",b,a);x(b,a,c)});a.find(".min-select").on("change click",function(){x(b,a,c)});a.on("focusout",function(){setTimeout(function(){var d=u(c);!d.length||c.is(":focus")||d.find(":focus").length||(b.selectOnBlur&&x(b,a,c),v(c))},50)});a.find(".ok-button").on("click",function(){x(b,a,c);v(c);c.trigger("change")});a.find(".cancel-button").on("click",function(){v(c)})}function G(a,c){var b=c.data("timepicker-settings"),
d=I(c.val(),b.timeFormat,b.ampmText),e=a.find(".hour-select").get(0),k=a.find(".min-select").get(0);if(null!=d){var g=d%60;if(b.use12HourClock){var h=Math.floor(d/60)%12;h=0!=h?h:12;d=720>d?"am":"pm";a.find(".ampm-button").text(d)}else h=Math.floor(d/60);z("hour",b,a);t(e,h)?A("minute",b,a):z("minute",b,a);t(k,g)}else b.scrollDefault&&(d=r(b.scrollDefault),null!=d&&(g=d%60,b.use12HourClock?(h=Math.floor(d/60)%12,h=0!=h?h:12,d=720>d?"am":"pm",a.find(".ampm-button").text(d)):h=Math.floor(d/60))),z("hour",
b,a),z("minute",b,a);c.offset();c.offset();c.outerHeight();a.insertAfter(c);"undefined"!==typeof h&&(t(e,h),C(e,h));"undefined"!==typeof g&&(t(k,g),D(k,g))}function u(a){return a.next(".my-timepicker-div")}function v(a){a.next(".my-timepicker-div").remove()}var B={init:function(a){var c=n.extend({},n.fn.timepicker.default_options,a),b={hour_data_24:null,hour_data_am:null,hour_data_pm:null,is_set_minmax_time:!1,is_set_time_step:!1,is_set_disabled_time:!1};a=0;var d=1439;c.minTime&&(a=r(c.minTime),
b.is_set_minmax_time=!0);c.maxTime&&(d=r(c.maxTime),b.is_set_minmax_time=!0);if(c.timeStep){b.is_set_time_step=!0;var e=1}else e=c.hourStep;c.disableTimeRanges&&(b.is_set_disabled_time=!0);c.use12HourClock?(e=y(a,d,e),b.hour_data_am=e.filter(function(f){return 12>f}).map(function(f){return 0!=f?{hour:f}:{hour:12}}),b.hour_data_pm=e.filter(function(f){return 12<=f}).map(function(f){return 12!=f?{hour:f%12}:{hour:12}}),12>e[0]?b.hour_data_am[0].min_minute=a%60:b.hour_data_pm[0].min_minute=a%60,12>e[e.length-
1]?b.hour_data_am[b.hour_data_am.length-1].max_minute=d%60:b.hour_data_pm[b.hour_data_pm.length-1].max_minute=d%60):(b.hour_data_24=y(a,d,e).map(function(f){return{hour:f}}),b.is_set_minmax_time&&(b.hour_data_24[0].min_minute=a%60,b.hour_data_24[b.hour_data_24.length-1].max_minute=d%60));if(b.is_set_disabled_time){a=c.disableTimeRanges.length;for(var k=0;k<a;k++){var g=r(c.disableTimeRanges[k][0]),h=r(c.disableTimeRanges[k][1]);c.use12HourClock?(b.hour_data_am.forEach(function(f){var l=f.hour%12;
60*l==g-g%60&&(f["disable_start_minute"+k]=g%60);60*l==h-h%60&&(f["disable_end_minute"+k]=disalbe_end%60);p(60*l,g,h)&&p(60*l+59,g,h)&&(f.disabled=!0)}),b.hour_data_pm.forEach(function(f){var l=f%12+12;60*l==g-g%60&&(f["disable_start_minute"+k]=g%60);l==h-h%60&&(f["disable_end_minute"+k]=h%60);p(60*l,g,h)&&p(60*l+59,g,h)&&(f.disabled=!0)})):b.hour_data_24.forEach(function(f){var l=f.hour;60*l==g-g%60&&(f["disable_start_minute"+k]=g%60);60*l==h-h%60&&(f["disable_end_minute"+k]=h%60);p(60*l,g,h)&&p(60*
l+59,g,h)&&(f.disabled=!0)})}}return this.each(function(){var f=n.extend({},c,b),l=n(this);l.data("timepicker-settings",f);"INPUT"===l.prop("tagName")&&(l.attr({placeholder:"--:--"}),l.on("focus.timepicker",function(){var m=n(this);if(!u(m).length){var w=E(m);F(w,m);G(w,m)}}),l.on("blur.timepicker",function(){var m=n(this);setTimeout(function(){var w=u(m);!w.length||m.is(":focus")||w.find(":focus").length||(f.selectOnBlur&&x(f,w,m),v(m))},50)}),l.on("change.timepicker",function(){var m=n(this);H(m.val(),
f.timeFormat,f.ampmText)||m.val("")}))})},setup:function(a){return this.each(function(){var c=n.extend({},base_data,other_data);n(this).data("timepicker-settings",c)})},option:function(a){return this.each(function(){var c=n(this).data("timepicker-settings");c="undefined"===typeof c?n.extend({},n.fn.timepicker.default_options,a):n.extend({},c,a);var b={hour_data_24:null,hour_data_am:null,hour_data_pm:null,is_set_minmax_time:!1,is_set_time_step:!1,is_set_disabled_time:!1},d=0,e=1439;c.minTime&&(d=r(c.minTime),
b.is_set_minmax_time=!0);c.maxTime&&(e=r(c.maxTime),b.is_set_minmax_time=!0);if(c.timeStep){b.is_set_time_step=!0;var k=1}else k=c.hourStep;c.disableTimeRanges&&(b.is_set_disabled_time=!0);c.use12HourClock?(k=y(d,e,k),b.hour_data_am=k.filter(function(l){return 12>l}).map(function(l){return 0!=l?{hour:l}:{hour:12}}),b.hour_data_pm=k.filter(function(l){return 12<=l}).map(function(l){return 12!=l?{hour:l}:{hour:12}}),12>k[0]?b.hour_data_am[0].min_minute=d%60:b.hour_data_pm[0].min_minute=d%60,12>k[k.length-
1]?b.hour_data_am[b.hour_data_am.length-1].max_minute=e%60:b.hour_data_pm[b.hour_data_pm.length-1].max_minute=e%60):(b.hour_data_24=y(d,e,k).map(function(l){return{hour:l}}),b.is_set_minmax_time&&(b.hour_data_24[0].min_minute=d%60,b.hour_data_24[b.hour_data_24.length-1].max_minute=e%60));if(c.disableTimeRanges){d=c.disableTimeRanges.length;for(var g=0;g<d;g++){var h=r(c.disableTimeRanges[g][0]),f=r(c.disableTimeRanges[g][1]);c.use12HourClock?(b.hour_data_am.forEach(function(l){var m=l.hour%12;60*
m==h-h%60&&(l["disable_start_minute"+g]=h%60);60*m==f-f%60&&(l["disable_end_minute"+g]=disalbe_end%60);p(60*m,h,f)&&p(60*m+59,h,f)&&(l.disabled=!0)}),b.hour_data_pm.forEach(function(l){var m=l%12+12;60*m==h-h%60&&(l["disable_start_minute"+g]=h%60);m==f-f%60&&(l["disable_end_minute"+g]=f%60);p(60*m,h,f)&&p(60*m+59,h,f)&&(l.disabled=!0)})):b.hour_data_24.forEach(function(l){var m=l.hour;60*m==h-h%60&&(l["disable_start_minute"+g]=h%60);60*m==f-f%60&&(l["disable_end_minute"+g]=f%60);p(60*m,h,f)&&p(60*
m+59,h,f)&&(l.disabled=!0)})}}c=n.exnted({},c,b);n(this).data("timepicker-settings",c)})},show:function(){return this.each(function(){var a=n(this);if(!a.data("timepicker-settings"))return!1;if(!u(a).length){var c=E(a);F(c,a);G(c,a)}return!1})},hide:function(){return this.each(function(){var a=n(this);u(a).length&&v(a)})},remove:function(){return this.each(function(){var a=n(this);u(a).length&&v(a);a.removeData("timepicker-settings");a.off(".timepicker")})}};n.fn.timepicker=function(a){if(!this.length)return this;
if(B[a])return B[a].apply(this,Array.prototype.slice.call(arguments,1));if("object"!==typeof a&&a)n.error("Method "+a+" does not exist on jQuery.timepicker");else return B.init.apply(this,arguments)};n.fn.timepicker.default_options={ampmText:{am:"am",pm:"pm",AM:"AM",PM:"PM"},hourHeaderText:"hour",minHeaderText:"min",okButtonText:"&#10004;",cancelButtonText:"&#10005;",hourStep:1,minStep:1,timeStep:null,minTime:null,maxTime:null,disableTimeRanges:null,scrollDefault:null,selectOnBlur:!1,selectSize:8,
timeFormat:"%H:%i",use12HourClock:!1}})(jQuery);
